name: Mutation Nightly

on:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch:

jobs:
  mutation-nightly:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
          python -m pip install pre-commit
      - name: Run full mutation suite
        run: python scripts/run_quality.py --output codex-report.json
      - name: Upload mutation report
        uses: actions/upload-artifact@v4
        with:
          name: mutation-report-${{ github.run_id }}
          path: |
            codex-report.json
            codex_logs
            mutmut.log
            mutmut.results
